"""Initial models

Revision ID: 041086a0a8a9
Revises:
Create Date: 2026-05-05 01:12:22.884113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '041086a0a8a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('dynasty', sa.String(length=64), nullable=True),
    sa.Column('stage_key', sa.String(length=64), nullable=True),
    sa.Column('stage_label', sa.String(length=128), nullable=True),
    sa.Column('year_range', sa.String(length=128), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('hero_lines', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poems_external_id'), ['external_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_poems_title'), ['title'], unique=False)

    op.create_table('learning_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poem_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['poem_id'], ['poems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poem_id', 'name', name='uq_poem_module')
    )
    with op.batch_alter_table('learning_modules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_modules_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_modules_name'))

    op.drop_table('learning_modules')
    with op.batch_alter_table('poems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poems_title'))
        batch_op.drop_index(batch_op.f('ix_poems_external_id'))

    op.drop_table('poems')
    # ### end Alembic commands ###


